### ISSUE TITLE
Update bestbets-loader to use @elastic/elasticsearch

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/bestbets-loader#20]
The elasticsearch package has been deprecated and is no longer maintained. The official client is the @elastic/elasticsearch package, which appears to be required in order to work with Elasticsearch 7.

**Parent Issue:** #19 

### Notes

- [Breaking changes/migration guide](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/7.17/breaking-changes.html)

**Comment by blairl-nih** [comment]
This is part of #19
